name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Code Check
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - run: node -v
      - uses: actions/checkout@v6
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: node -v
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - run: node -v
      - name: Code check
        run: bun run check
