name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # TODO: delete this after 2026-06
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Code check
        run: bun run check
